apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-iroq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0032-tenant/tkrw-pr712-0075-0032-app/devfile-sample-iroq@sha256:d8259e1cfb6b585570dcc381c105946f03aed14b82441df2d2f2759267d645b5
        name: my-nodejs
        resources: {}
status: {}
